export type CourseCategory = 'inicio' | 'programacion' | 'proyectos';

export interface Course { slug: string; title: string; description: string; category: CourseCategory; level: string; lessons: string; url: string; thumbnail: string; }
export interface Project { title: string; description: string; technologies: string[]; repoUrl: string; liveUrl?: string; accent: string; }

export const courses: Course[] = [
  { slug: 'pseint-desde-cero', title: 'Lógica de Programación con PSeInt', description: 'Domina algoritmos, variables, condicionales y ciclos con ejercicios progresivos desde cero.', category: 'inicio', level: 'Principiante', lessons: '47 lecciones', url: 'https://www.youtube.com/playlist?list=PLZmtYtnx3IcUR9P1pZ7VOWlzvizYB6EF-', thumbnail: 'https://i.ytimg.com/vi/I9zCEqyDeYg/hqdefault.jpg' },
  { slug: 'html5-desde-cero', title: 'HTML5 desde Cero', description: 'Entiende cómo funciona la web y construye páginas con una base semántica sólida.', category: 'inicio', level: 'Principiante', lessons: '22 lecciones', url: 'https://www.youtube.com/playlist?list=PLZmtYtnx3IcUTlaEly3oC6LMpJJ3SmT2-', thumbnail: 'https://i.ytimg.com/vi/NmKc5o8tEgA/hqdefault.jpg' },
  { slug: 'python-30-dias', title: 'Aprende Python en 30 Días', description: 'Una ruta diaria y práctica para dar tus primeros pasos con Python y ganar constancia.', category: 'programacion', level: 'Principiante', lessons: '30 lecciones', url: 'https://www.youtube.com/playlist?list=PLZmtYtnx3IcV8Be2ld0-vOwev5Hxw13ho', thumbnail: 'https://i.ytimg.com/vi/izEmMKkakac/hqdefault.jpg' },
  { slug: 'javascript-esencial', title: 'JavaScript Esencial', description: 'Aprende los conceptos que hacen que tus interfaces cobren vida en el navegador.', category: 'programacion', level: 'Principiante', lessons: '5 videos', url: 'https://www.youtube.com/playlist?list=PLZmtYtnx3IcURKJyzil6hk4-e_Zn5FKTY', thumbnail: 'https://i.ytimg.com/vi/G_8ryIgbRZw/hqdefault.jpg' },
  { slug: 'mysql-bases-datos', title: 'MySQL y Bases de Datos', description: 'Crea tablas, relaciona información y practica SQL con un proyecto real en MySQL Workbench.', category: 'programacion', level: 'Principiante', lessons: '5 videos', url: 'https://www.youtube.com/playlist?list=PLZmtYtnx3IcVKflKV9VoSXs3uce1_knMX', thumbnail: 'https://i.ytimg.com/vi/jRSv4ERH9Dg/hqdefault.jpg' },
  { slug: 'react-js', title: 'Aprende React JS', description: 'Primeros componentes y conceptos de React para llevar tus interfaces al siguiente nivel.', category: 'programacion', level: 'Intermedio', lessons: '2 videos', url: 'https://www.youtube.com/playlist?list=PLZmtYtnx3IcXsIHRNMg3TzssSsp-PQ3PI', thumbnail: 'https://i.ytimg.com/vi/4tVy4A1WDlY/hqdefault.jpg' },
  { slug: 'cpp', title: 'Todo sobre C++', description: 'Ejercicios y proyectos para practicar lógica y programación estructurada con C++.', category: 'programacion', level: 'Principiante', lessons: '5 videos', url: 'https://www.youtube.com/playlist?list=PLZmtYtnx3IcXg71iKA-0QR_c9oA50EWyM', thumbnail: 'https://i.ytimg.com/vi/q-Gb2hDR2Gc/hqdefault.jpg' },
  { slug: 'proyectos-javascript', title: 'Proyectos con JavaScript', description: 'Construye interfaces y utilidades reales mientras dominas el DOM y la lógica del navegador.', category: 'proyectos', level: 'Práctico', lessons: '44 videos', url: 'https://www.youtube.com/playlist?list=PLZmtYtnx3IcX1NV76bJym4KYG95SC60iq', thumbnail: 'https://i.ytimg.com/vi/ZSSOiJaMIk0/hqdefault.jpg' },
  { slug: 'carrito-compras', title: 'Carrito de Compras', description: 'Maqueta y programa un carrito de compras completo con HTML, CSS y JavaScript.', category: 'proyectos', level: 'Práctico', lessons: '3 videos', url: 'https://www.youtube.com/playlist?list=PLZmtYtnx3IcUJJXViV5yN9nKDbpIbDDq-', thumbnail: 'https://i.ytimg.com/vi/I9byWaeC9e8/hqdefault.jpg' },
  { slug: 'formularios-fullstack', title: 'Formulario, PHP y MySQL', description: 'Desarrolla, valida y conecta un formulario con PHP y una base de datos MySQL.', category: 'proyectos', level: 'Intermedio', lessons: '5 lecciones', url: 'https://www.youtube.com/playlist?list=PLZmtYtnx3IcX1PXnSdrn0G80iO2mwD9Cr', thumbnail: 'https://i.ytimg.com/vi/nLvg_sqNYB0/hqdefault.jpg' },
];

export const featuredCourses = courses.slice(0, 3);

export const projects: Project[] = [
  { title: 'Votómetro', description: 'Plataforma cívica para explorar afinidades con propuestas de las Elecciones Perú 2026 de forma clara y accesible.', technologies: ['HTML', 'CSS', 'JavaScript', 'Datos'], repoUrl: 'https://github.com/DaniCodex/votometro', liveUrl: 'https://votometrolat.com/', accent: 'blue' },
  { title: 'Flores Amarillas', description: 'Experiencia web interactiva que combina animación, música y creatividad con tecnologías web.', technologies: ['HTML', 'CSS', 'JavaScript'], repoUrl: 'https://github.com/DaniCodex/flores-amarillas-tres', accent: 'yellow' },
  { title: 'Formulario Dinámico', description: 'Interfaz animada de registro e inicio de sesión construida desde cero para enseñar fundamentos frontend.', technologies: ['HTML', 'CSS', 'JavaScript'], repoUrl: 'https://github.com/DaniCodex/Formulario-dinamico-HTML-CSS-JS', accent: 'cyan' },
  { title: '100 Proyectos con JavaScript', description: 'Reto progresivo de proyectos con JavaScript puro: DOM, APIs, estado, LocalStorage y lógica de negocio.', technologies: ['JavaScript', 'APIs', 'LocalStorage'], repoUrl: 'https://github.com/DaniCodex/100-proyectos-javascript', accent: 'orange' },
  { title: 'Sistema de Biblioteca', description: 'Simulación de gestión de una biblioteca digital desarrollada para practicar estructuras y lógica con C++.', technologies: ['C++', 'POO', 'Consola'], repoUrl: 'https://github.com/DaniCodex/sistema-bibloteca-cpp', accent: 'purple' },
];
